#! /usr/bin/env ruby

%x{scp thepavedearth.com:stadiumchoir.twoedge.com/db/production.sqlite3 db/production_bak.sqlite3}

timestamp = Time.now.strftime("%Y%m%d")
bak_file = "db/production_bak.sqlite3"
incremental_bak_file = "db/bak/#{timestamp}_#{File.basename(bak_file)}"

begin
  if File::Stat.new(bak_file).size > File::Stat.new(incremental_bak_file).size
    %x{cp #{bak_file} #{incremental_bak_file}}
  end
rescue
  %x{cp #{bak_file} #{incremental_bak_file}}  # do the copy if the file doesn't exist
end
